### PR TITLE
Creating simple Durable Function in the Azure portal

### PR DESCRIPTION
**Pull request by gled4er**
Hello All,

May I ask you to review this pull request containing instructions for creating Durable Function from the templates available in the Azure Portal?

Thank you!

### CODE REVIEW

**Comment by TsuyoshiUshio** [comment]
Hi @gled4er , I can't see the binary image, however, I reviewed. Looks great!  

I recommend to have a link for the Durable Functions useful links on the last just if you like. :) 
Other concern is this is for functions v2. Is this valid now? I mean you create this before the breaking change. If it's OK. It's perfect!

**Comment by gled4er** [comment]
Hello @TsuyoshiUshio,

Thank you very much for the review!

You can see the images as well [here](https://github.com/codingwithsasquatch/serverless_ninjas_workshop/tree/feature/add-durable-functions-portal-lab/8-Durable_Functions_Lab)

I used the template that is provided in the portal. I haven't tried it since 2 weeks age, I will do it today or tomorrow and fix accordingly.

Thank you for the great points!

**Review by yokawasa — COMMENTED** [review]
@gled4er Sorry for the delay. Looks great to me!

One thing: 
For "what's more", It's good to add some references in this lab or overview part to show how they can start DF with JavaScript or how can have better development experience with VS or VSCode, etc.

**Comment by gled4er** [comment]
Hello @yokawasa,

Thank you very much for the great feedback. I will be working on fixing the issues you mentioned. 

Thank you!

**Pull request merged**
